### ISSUE TITLE
Not working on 1.2.0rc2 ?

### ISSUE THREAD

**Issue by pettai** [Graylog2/graylog-plugin-jabber#4]
Hi,

After triggering a stream alarm, I get this in the graylog-server log:

2015-09-07T11:05:54.421+02:00 WARN  [XMPPConnection] Connection closed with error
stream:error (host-unknown)
	at org.jivesoftware.smack.tcp.PacketReader.parsePackets(PacketReader.java:222)
	at org.jivesoftware.smack.tcp.PacketReader.access$000(PacketReader.java:47)
	at org.jivesoftware.smack.tcp.PacketReader$1.run(PacketReader.java:81)

And I never see a connection/authentication attempt on the jabber server...
 
(FYI, we run Ubuntu 14.04 and have installed graylog(-server + web) and the xmpp plugin using the available deb packages:

root@graylog:~# dpkg -l | grep graylog
ii  graylog-1.1-repository-ubuntu14.04   1.2.0-3                             all          Package to install Graylog 1.1 GPG key and repository
ii  graylog-1.2-repository-ubuntu14.04   1.2.0-4                             all          Package to install Graylog 1.2 GPG key and repository
ii  graylog-alarmcallback-jabber         1.1.0                               all          Graylog2 Jabber/XMPP Alarmcallback plugin
ii  graylog-server                       1.2.0-2.rc.2                        all          Graylog server
ii  graylog-web                          1.2.0-2.rc.2                        all          Graylog web)

**Comment by kroepke** [comment]
Is there more to the error message in the log? This seems a bit truncated.

**Comment by pettai** [comment]
Right, there was another message shortly after:

2015-09-07T11:05:59.421+02:00 WARN  [AlertScannerThread] Alarm callback <Jabber Alarm Callback> failed. Skipping.
org.graylog2.plugin.alarms.callbacks.AlarmCallbackException: Unable to connect to jabber server:
        at org.graylog2.alarmcallbacks.jabber.JabberAlarmCallback.call(JabberAlarmCallback.java:123)
        at org.graylog2.periodical.AlertScannerThread.doRun(AlertScannerThread.java:113)
        at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:83)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.jivesoftware.smack.SmackException$NoResponseException
        at org.jivesoftware.smack.XMPPConnection.throwConnectionExceptionOrNoResponse(XMPPConnection.java:548)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.throwConnectionExceptionOrNoResponse(XMPPTCPConnection.java:867)
        at org.jivesoftware.smack.tcp.PacketReader.startup(PacketReader.java:113)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.initConnection(XMPPTCPConnection.java:482)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:440)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:811)
        at org.jivesoftware.smack.XMPPConnection.connect(XMPPConnection.java:396)
        at org.graylog2.alarmcallbacks.jabber.JabberAlarmCallback.login(JabberAlarmCallback.java:86)
        at org.graylog2.alarmcallbacks.jabber.JabberAlarmCallback.call(JabberAlarmCallback.java:121)
        ... 9 more

**Comment by pettai** [comment]
(and more FYI, where running graylog on OpenJDK
ii  openjdk-7-jre-headless:amd64         7u79-2.5.6-0ubuntu1.14.04.1         amd64        OpenJDK Java runtime, using Hotspot JIT (headless))

**Comment by kroepke** [comment]
I've just tested it locally with a prosody server, using SASL and it works as expected.

The second error messages indicates that the Jabber server could not be reached, or did not respond. This does not look like a bug to me, but instead like a misconfiguration. Please check that you can reach the host and port from the Graylog server.

The plugin works fine with 1.2.x, so I'm closing this here.

**Comment by pettai** [comment]
I seems to be a interop thing between the plugin and ejabberd. I've tried against two different xmpp servers running ejabberd, but there is no authentication according to the logs. (At least TCPdump shows packets exchanged). I'll open a new issue, pointing in that direction then...

**Comment by kroepke** [comment]
For the record, when testing I had to leave out the domain name from the user account used to authenticate, otherwise I got SASL errors as well, maybe that helps.
However, I don't think anything has changed in the plugin so if it worked before there's no reason why it should stop working.

**Comment by pettai** [comment]
We've tested with and without realm on the username, it made no difference.
I noticed @jjoschi bumped smack to the latest release, maybe it will work better
